#create workflow
name: Hello Workflow
# Triggering for run
on:
  push:
    branches: [main]
jobs:
  #job1
  greet:
    #runner for every job
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello"
      - name: say hello to user
        run: echo "hello $USER"
